### ISSUE TITLE
dataset Preparation 

### ISSUE THREAD

**Issue by awais00012** [summitgao/HCANet#1]
hi there, great work you have done. could you please tell us about the dataset preparation. Well, is it customizable based on own data?

**Comment by summitgao** [comment]
We are delighted to see your interest in our work. 
To obtain details of the dataset, you can contact Hu Shuai by sending an email: 	
1529270914@qq.com

**Comment by hushuaiouc** [comment]
Of course, you can use your own data, just set the shape of the dataset. In my work, I use the ICVL dataset and crop it to a size of 128x128x31 for training. For specific training details, please refer to this repository: https://github.com/summitgao/MAFNet
