### ISSUE TITLE
Some confusion about the module OverlapPatchEmbed

### ISSUE THREAD

**Issue by D-Walter** [summitgao/HCANet#2]
Hi,

First of all, thank you for your excellent work on this project. It has been incredibly insightful and helpful.

I have a small confusion regarding the design of the OverlapPatchEmbed module. Upon examining the code, it appears that the 3x3x3 convolution operation effectively degenerates into a simple 3x3 2D convolution. Specifically, the input tensor is unsqueezed to add an additional dimension, processed with a 3D convolution, and then the extra dimension is removed.

This process seems to imply that the 3D convolution is effectively acting as a 2D convolution. Could you please provide further clarification on this design choice and its implications?

Here is the relevant code snippet for reference:

https://github.com/summitgao/HCANet/blob/0c7d03b8013d6b89a71bb9368d8bc1fbb290b0c0/HCANet.py#L187-L198

**Comment by hushuaiouc** [comment]
thank for your question, many studies have indicated that using 3D convolutions to process hyperspectral data yields better results. Therefore, in this approach, we map the data into a 4-dimensional space through dimensional transformation to utilize 3D convolutions. This practice also draws on some previous research work from ICCV2023 HSDT. Thank you for your attention.
